openapi: 3.1.0
info:
  title: "{{translate workspace.name}}"
  version: "1.0.0"
  description: |
    Generated by Doklo Live Docs from {{len doks}} Hub Doks.
    Endpoints lacking code-extracted shape carry x-doklo-status: stub —
    real endpoint extraction is deferred to v1.x.
servers:
  - url: "/api"
    description: "Default server"
paths:
  /:
    get:
      summary: "Root"
      x-doklo-status: stub
      responses:
        '200':
          description: OK
{{#each doks}}
{{#unless (eq this.status "archived")}}
  /doks/{{this.dok_id}}:
    get:
      summary: "{{translate this.name}}"
      description: "{{translate this.description}}"
      tags: [{{#each this.tags}}{{#if @index}}, {{/if}}"{{this}}"{{/each}}]
      x-doklo-status: stub
      x-doklo-dok-id: "{{this.dok_id}}"
      x-doklo-status-field: "{{this.status}}"
      responses:
        '200':
          description: "OK"
{{/unless}}
{{/each}}
components:
  schemas:
    DoklStub:
      type: object
      description: "Placeholder schema. Real schemas land when endpoint extraction ships."
